# Generated by Django 2.0.2 on 2018-06-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('view_article', '看文章的权限！')]},
        ),
    ]
