# Generated by Django 2.0.2 on 2018-04-16 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_article_create_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_time',
        ),
    ]
