# Generated by Django 2.0 on 2019-04-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190406_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
    ]
