# Generated by Django 2.0.2 on 2018-04-04 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_auto_20180404_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='create_time',
        ),
    ]
