# Generated by Django 2.0.2 on 2018-04-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20180404_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
