# Generated by Django 2.0.2 on 2018-03-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_author_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
