# Generated by Django 2.0 on 2019-04-16 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190416_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='target',
            new_name='post',
        ),
    ]
