# Generated by Django 2.1.3 on 2019-03-08 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siderbar',
            old_name='context',
            new_name='content',
        ),
    ]
